#!/usr/bin/env zsh

zstyle ':autocomplete:*' fzf-completion yes
zstyle ':autocomplete:recent-dirs' backend zoxide

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

PROMPT_EOL_MARK=''
ENABLE_CORRECTION="true"

# History
HIST_STAMPS="yyyy-mm-dd"
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=290000
SAVEHIST=$HISTSIZE
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_all_dups   # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
unsetopt share_history

# Other options
setopt always_to_end # cursor moved to the end in full completion
setopt hash_list_all # hash everything before completion
setopt always_to_end
setopt complete_in_word
setopt nocorrect      # spelling correction for commands
setopt list_ambiguous # complete as much of a completion until it gets ambiguous.
setopt nolisttypes
setopt listpacked
setopt automenu

source "$HOME"/.local/share/zsnap/znap.zsh

znap source ohmyzsh/ohmyzsh \
  lib/{clipboard,compfix,completion,correction,directories,git,grep,history,spectrum,termsupport} \
  plugins/{fzf,git,gpg-agent}

znap source chrissicool/zsh-256color
znap source zdharma-continuum/fast-syntax-highlighting
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions
znap source marlonrichert/zsh-autocomplete
znap eval trapd00r/LS_COLORS "$(whence -a dircolors gdircolors) -b LS_COLORS"
znap source unixorn/fzf-zsh-plugin

for f in ${ZDOTDIR:-$HOME/.config/zsh}/*.zsh; do
  source "${f}"
done
