#!/usr/bin/env zsh

zstyle ':autocomplete:*' fzf-completion yes
zstyle ':autocomplete:recent-dirs' backend zoxide

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

PROMPT_EOL_MARK=''
unsetopt share_history
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"

for f in ${ZDOTDIR:-$HOME/.config/zsh}/*.zsh; do
  source "${f}"
done
