{{- if eq .chezmoi.os "linux" }}
[".local/bin/age"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" (printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) | quote }}
    executable = true
    path = "age/age"

[".local/bin/age-keygen"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "FiloSottile/age" (printf "age-*-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) | quote }}
    executable = true
    path = "age/age-keygen"

[".local/bin/starship"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "starship/starship" "starship-x86_64-unknown-linux-musl.tar.gz" | quote }}
    executable = true
    path = "starship"

[".local/share/znap"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-snap.git"
    refreshPeriod = "168h"

[".local/bin/yq"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "mikefarah/yq" (printf "yq_%s_%s" .chezmoi.os .chezmoi.arch) | quote }}
    executable = true
    path = "age/age"

[".local/share/nano-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/galenguyer/nano-syntax-highlighting"
    refreshPeriod = "168h"
{{- end }}

{{- $fontDir := "" }}
{{- if eq .chezmoi.os "linux" }}
{{-   $fontDir = ".local/share/fonts" }}
{{- end }}

{{- if ne "{{ $fontDir }}" "" }}
[jetbrains_mono]
    type = "archive"
    url = {{ gitHubLatestReleaseAssetURL "ryanoasis/nerd-fonts" "JetBrainsMono.tar.xz" | quote }}
    include = ["**/*.ttf"]
    refreshPeriod = "168h"
    targetPath = "{{ $fontDir }}"
{{- end }}
